Update the CTA for "Don't yet have KEEP?"
keep-network/keep-core pull request #2284
Opened 2021-01-12 14:58 UTC by michalsmiarowski

Closes: #2263 

Update the CTA for "Don't yet have KEEP?" to link to exchange instead of Discord.

![image](https://user-images.githubusercontent.com/40306834/104330994-dc4e4a00-54ee-11eb-8422-15be6f3d78df.png)

2021-01-13 11:15 UTC, r-czajkowski requested changes
Just two very tiny comments. Looking good 👍.

2021-01-13 11:15 UTC, r-czajkowski commented on solidity/dashboard/src/pages/OverviewPage.jsx
> +          <Icons.BalancerLogo />{" "}
Could we use `&nbsp;` instead of `{" "}`?

2021-01-13 11:15 UTC, r-czajkowski commented on solidity/dashboard/src/pages/OverviewPage.jsx
> +          <Icons.UniswapLogo style={{ verticalAlign: "text-top" }} />{" "}
same as above.

2021-01-14 07:54 UTC, michalsmiarowski commented
I fixed those two minor issues you mentioned in comments. PR is ready for another code review round!

2021-01-14 08:41 UTC, r-czajkowski approved these changes

2021-01-14 08:42 UTC, merged