Support WalletConnect
keep-network/keep-core pull request #2340
Opened 2021-02-22 15:25 UTC by r-czajkowski

Closes: #1751 
WIP...

2021-03-15 14:19 UTC, michalsmiarowski requested changes
Looking nice. Tested with `walletconnect-test-wallet` and it's working fine. Left some comments that you might want to look at

2021-03-17 12:03 UTC, r-czajkowski commented on solidity/dashboard/src/components/Web3ContextProvider.jsx
> +      )
It could be helpful if a user will have an issue with a wallet connection.

2021-03-17 12:26 UTC, r-czajkowski commented on solidity/dashboard/src/components/LedgerModal.jsx
> +      icon={<Icons.Ledger class="ledger-logo--black" />}
You are right. We need to go through our CSS code and update based on BEM but think we should create a separate issue for this.

2021-03-22 13:48 UTC, michalsmiarowski approved these changes
Looking good to me 👍 Tested it on Ropsten and had no issues.

2021-03-23 07:18 UTC, Battenfield approved these changes
LGTM - QA once it is built in the environment

2021-03-23 11:43 UTC, merged