Calculate reward multiplier
keep-network/keep-core pull request #2386
Opened 2021-03-18 11:43 UTC by michalsmiarowski

Closes: #2328 

WIP

2021-03-24 11:25 UTC, r-czajkowski requested changes

2021-03-24 11:25 UTC, r-czajkowski commented on solidity/dashboard/src/sagas/liquidity-rewards.js
> +    const rewardMultiplier = yield call(
We probably should update `rewardMultiplier` when the user has withdrawn or deposited more tokens.

2021-03-24 11:25 UTC, r-czajkowski commented on solidity/dashboard/src/components/liquidity/RewardMultiplier.jsx
> +  return <>Reward multiplier tooltip</>
I realize that we don't have wireframes for this but maybe: `Deposit liquidity tokens for 30 days to achieve a 3x reward multiplier.` + something about how we calculate it? I mean we take into account all stakes. What do you think?

2021-03-26 11:33 UTC, michalsmiarowski commented
Ready for another round of review @r-czajkowski

2021-03-29 13:49 UTC, r-czajkowski approved these changes
LGTM!

2021-03-30 08:09 UTC, merged