Fix Reward Multiplier calculation
keep-network/keep-core pull request #2425
Opened 2021-04-16 14:59 UTC by michalsmiarowski

WIP

2021-04-21 12:57 UTC, r-czajkowski requested changes
Looking good and it works as expected 🚀 . Let's just add some unit tests for `scaleInputForNumberRange` function.

2021-04-21 12:57 UTC, r-czajkowski commented on solidity/dashboard/src/utils/general.utils.js
> +export const scaleInputForNumberRange = (inputX, xMin, xMax, yMin, yMax) => {
Could we add some tests for this function?

2021-04-21 13:37 UTC, r-czajkowski requested changes
Just a tiny comment.

2021-04-21 13:37 UTC, r-czajkowski commented on solidity/dashboard/src/utils/general.utils.js
> + * number line of <1, 10> it will return 5.
It will return `5.5` instead of `5`.

2021-04-21 13:46 UTC, michalsmiarowski commented on solidity/dashboard/src/utils/general.utils.js
> + * number line of <1, 10> it will return 5.
That's right! Thanks 🔥

2021-04-22 06:15 UTC, r-czajkowski approved these changes
:shipit:

2021-04-22 06:16 UTC, merged