KEEP Token Dashboard v1.14.0 release
keep-network/keep-core pull request #2471
Opened 2021-05-18 14:37 UTC by r-czajkowski

KEEP Token Dashboard v1.14.0 release branch. This release will bundle the work from https://github.com/keep-network/keep-core/milestone/50?closed=1

2021-05-18 15:09 UTC, michalinacienciala commented
@r-czajkowski , there is a global outage of GH Actions today, that's why no checks were executed. You can check current state of the incident [here](https://www.githubstatus.com/incidents/m16jzl31gnqt). You may need to re-run following workflows once the incident gets resolved:
https://github.com/keep-network/keep-core/actions/runs/853684933
https://github.com/keep-network/keep-core/actions/runs/853684934
https://github.com/keep-network/keep-core/actions/runs/853684935
https://github.com/keep-network/keep-core/actions/runs/853684937

2021-05-31 13:03 UTC, michalsmiarowski requested changes
Looks like there is a bug with modal window titles. They are not displaying probably because of changes from #2444

2021-06-01 07:23 UTC, michalsmiarowski approved these changes
The modal window's bug was fixed in #2486. Tested the preview locally and it's looking good 👍

2021-06-01 10:24 UTC, pdyraga commented on infrastructure/kube/keep-prd/keep-dapp-token-dashboard-deployment.yaml
> +        image: keepnetwork/token-dashboard:v1.14.0
Let's prepare a separate PR to increase the `master` `version` in `package.json` to `1.15.0-pre` and that changes this line to `v1.14.0` just like it is done here.

2021-09-30 17:53 UTC, closed without merging