Storybook for dashboard
keep-network/keep-core pull request #2472
Opened 2021-05-18 15:54 UTC by michalsmiarowski

WIP...

2021-05-28 07:55 UTC, r-czajkowski requested changes
Left couple of notes. Overall looking good. I would just consider removing the bigger components or create a kind of hierarchy. Eg `components` for the smallest components in the dapp, `views/templates` for the bigger one eg. forms. I was wondering about the naming convention of the atomic design (atoms/molecules/organisms etc), but that would require a rebuild of almost the entire dapp.

2021-05-28 07:55 UTC, r-czajkowski commented on solidity/dashboard/src/stories/WalletConnectModal.stories.js
> +  component: WalletConnectModal,
Each story for modal has transparent background. Can we set white background by default?

2021-05-28 07:55 UTC, r-czajkowski commented on solidity/dashboard/src/stories/Web3Status.stories.js
> +  isConnected: true,
If we set `isConnected` to `true`, the `network disconnected` is displayed. Can we fix it?

2021-05-28 07:55 UTC, r-czajkowski commented on solidity/dashboard/src/stories/TransactionIsPendingMsgContent.stories.js
> +  component: TransactionIsPendingMsgContent,
This component is no longer used- so I think we can remove this story and get rid of this component from the dapp.

2021-05-28 07:55 UTC, r-czajkowski commented on solidity/dashboard/src/stories/ApplicationBox.stories.js
> +  component: ApplicationBox,
The `ApplicationBox` is also no longer used. Let's remove story and component.

2021-05-28 07:55 UTC, r-czajkowski commented on solidity/dashboard/src/stories/TBTCRewardsDataTable.stories.js
> +  component: TBTCRewardsDataTable,
Transparent background- it also applies to some other data tables components eg. `SlashedTokensList`.

2021-07-09 11:52 UTC, r-czajkowski reviewed
Shouldn't we add `storybook-static` dir genereted by `npm run build-storybook` to the `gitignore`?

2021-07-14 10:18 UTC, r-czajkowski approved these changes
LGTM! Left a final approval for @Battenfield

2026-06-01 19:24 UTC, lionakhnazarov commented
Closing — Storybook for the dashboard; the dashboard has been extracted to its own repository, so this no longer has a target here.

2026-06-01 19:24 UTC, closed without merging