Modal updates cov pools
keep-network/keep-core pull request #2685
Opened 2021-11-03 16:06 UTC by r-czajkowski

Ref: #2670 
WIP...

2021-11-08 10:08 UTC, michalsmiarowski requested changes
Left some comments, but overall good job!

2021-11-08 10:08 UTC, michalsmiarowski commented on solidity-v1/dashboard/src/components/modal/coverage-pools/components/WithdrawalOverview.jsx
> +    } else if (withdrawalDelay === PENDING_WITHDRAWAL_STATUS.COMPLETED) {
Should be `withdrawalStatus` here

```suggestion
    } else if (withdrawalStatus === PENDING_WITHDRAWAL_STATUS.COMPLETED) {
```

2021-11-08 12:19 UTC, r-czajkowski commented on solidity-v1/dashboard/src/components/modal/coverage-pools/components/WithdrawalOverview.jsx
> +    } else if (withdrawalDelay === PENDING_WITHDRAWAL_STATUS.COMPLETED) {
68f104f

2021-11-08 12:19 UTC, r-czajkowski commented on solidity-v1/dashboard/src/components/modal/coverage-pools/deposit/InitiateDeposit.jsx
> +          <form>
88d5760

2021-11-08 12:19 UTC, r-czajkowski commented on solidity-v1/dashboard/src/components/modal/coverage-pools/IncreaseWithdrawal.jsx
> +        <form>
88d5760

2021-11-08 12:19 UTC, r-czajkowski commented on solidity-v1/dashboard/src/components/modal/coverage-pools/deposit/InitiateDeposit.jsx
> +            Deposit
5c01248

2021-11-10 13:31 UTC, michalsmiarowski approved these changes
LGTM

2021-11-10 13:32 UTC, merged