Drafting functionality which updates gov. params
keep-network/keep-core pull request #2800
Opened 2022-01-27 13:46 UTC by dimpar

Refs #2758

Depends on #2775

Updating governance params.

2022-02-01 10:52 UTC, nkuba requested changes

2022-02-01 16:35 UTC, dimpar commented on solidity/ecdsa/test/fixtures/index.ts
> +export const dkgParams = {
f396c5b

2022-02-01 16:35 UTC, dimpar commented on solidity/ecdsa/contracts/WalletRegistry.sol
> +    function dkgResultParameters()
a5f236e

2022-02-01 16:36 UTC, dimpar commented on solidity/ecdsa/contracts/WalletRegistryGovernance.sol
> +    ///        of the change.
51c0273

2022-02-01 16:36 UTC, dimpar commented on solidity/ecdsa/contracts/WalletRegistryGovernance.sol
> +                .resultSubmissionEligibilityDelay,
3d6225f

2022-02-01 16:37 UTC, dimpar commented on solidity/ecdsa/contracts/WalletRegistry.sol
>      ) external {
9754e37

2022-02-01 16:37 UTC, dimpar commented on solidity/ecdsa/test/WalletRegistryGovernance.test.ts
> +    const WalletRegistryGovernance = await ethers.getContractFactory(
6837f64

2022-02-11 10:54 UTC, nkuba approved these changes
I don't see any blockers. We can handle my comments in a follow-up PR.

2022-02-11 10:54 UTC, nkuba commented on solidity/ecdsa/test/WalletRegistryGovernance.test.ts
> +          .beginDkgResultChallengePeriodLengthUpdate(10)
We could use `to.not.be.reverted` for verification (in other places too).

```suggestion
        await expect(
          walletRegistryGovernance
            .connect(governance)
            .beginDkgResultChallengePeriodLengthUpdate(10)
          ).to.not.be.reverted
```

2022-02-11 10:54 UTC, merged

2022-02-12 13:14 UTC, dimpar commented
> I don't see any blockers. We can handle my comments in a follow-up PR.

Follow up PR is ready https://github.com/keep-network/keep-core/pull/2820