Add workflow publishing ecdsa contracts for dev env
keep-network/keep-core pull request #2869
Opened 2022-03-15 09:20 UTC by michalinacienciala

We're adding a workflow which will publish a package with compiled
`ecdsa` contracts. Package will be meand for development purposes.

The `-dev` suffix will be used in the name of the published package.
The workflow will be triggered every time a change to contracts or
dependencies gets pushed to `main`. Also a change to the workflow file
will trigger the workflow.

As art of this PR we're also adding ignoring of `external` directory in git and linters.

TODO:
Once PR gets "pre-approved":
- [ ] Remove `--dry-run`
- [ ] Publish first NPM package
- [ ] Remove `npm-ecdsa` branch trigger
- [ ] Uncomment "Bump up package version" step

2022-03-15 09:21 UTC, michalinacienciala commented
@Kuba, please see if PR looks ok to you. Once I get a green light from you, I will perform steps from the TODO list and ask you for final PR approval.

2022-03-15 10:08 UTC, nkuba requested changes

2022-03-15 10:08 UTC, nkuba commented on .github/workflows/npm-ecdsa.yml
> +      - "solidity/ecdsa/contracts**"
Shouldn't it be `contracts/**`?
```suggestion
      - "solidity/ecdsa/contracts/**"
```

2022-03-15 10:08 UTC, nkuba commented on .github/workflows/npm-ecdsa.yml
> +      - "solidity/ecdsa/contracts**"
Let's also add `"solidity/ecdsa/deploy/**"` directory as we may use the deployment scripts in other projects.

2022-03-15 10:08 UTC, nkuba commented on .github/workflows/npm-ecdsa.yml
> +        run: npm publish --access=public --network=development --tag=development --dry-run
Looks like we don't use the `network` argument in the publication scripts in this project.

```suggestion
        run: npm publish --access=public --tag=development --dry-run
```

2022-03-15 10:08 UTC, nkuba commented on solidity/ecdsa/.gitignore
> +external/
Let's exclude `external/npm` directory as it contains the auto-generated content. We may want to add e.g. `external/mainnet` directory with hardcoded mainnet contracts to use.

```suggestion
external/npm
```

2022-03-15 10:08 UTC, nkuba commented on solidity/ecdsa/package.json
> +    "scripts/",
We don't have `scripts` directory in this project.
```suggestion
```

2022-03-17 12:44 UTC, nkuba commented
We need https://github.com/keep-network/keep-core/pull/2874 to get in before this one.

2022-03-22 13:15 UTC, nkuba submitted a review, later dismissed

2022-03-24 11:34 UTC, nkuba approved these changes

2022-03-24 11:53 UTC, merged